# Site settings
title: productive thinking
email: 
description: > # this means to ignore newlines until "baseurl:"
  Alexander Wang's personal blog
# baseurl: "/personal-blog" # the subpath of your site, e.g. /blog/
baseurl: ""
# url: "http://alexjwang.github.io" # the base hostname & protocol for your site
url: "https://alexjwang.com"
github_username: alexjwang

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

plugins: [jekyll-paginate]
paginate: 12
paginate_path: /page:num/

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]

